development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: SNDSTREAM_DEV
  pool: 5
  username: andy
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: SNDSTREAM_TEST
  pool: 5
  username: andy
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: SNDSTREAM_PROD
  pool: 5
  username: andy
  password:

